services:
  postgres:
    image: postgres:15
    container_name: ballot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ballot
      POSTGRES_PASSWORD: ballot
      POSTGRES_DB: ballotdb
    ports:
      - "5433:5432"
    volumes:
      - ballot_pgdata:/var/lib/postgresql/data

volumes:
  ballot_pgdata:
